server:
  port: 8888
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/safe_campus
    driver-class-name:
    username: root
    password: 12345678
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
    password: